SUBROUTINE INCVE
    use COMMON
    implicit none
    
    ELOAD = 0.d0
    
    DNEXT = FTIME * DTIME

    do IELEM = 1, NELEM

        NODE1 = LNODS(IELEM,1)
        NODE2 = LNODS(IELEM,2)
 
        DISP1=CALFA(IELEM)*XDISP(2*NODE1-1)+SALFA(IELEM)*XDISP(2*NODE1)
        DISP2=CALFA(IELEM)*XDISP(2*NODE2-1)+SALFA(IELEM)*XDISP(2*NODE2)

        DSPGX=SQRT(XDISP(2*NODE2-1)**2+XDISP(2*NODE1-1)**2)
        DSPGY=SQRT(XDISP(2*NODE2)**2+XDISP(2*NODE1)**2)
         
        LASTS(IELEM) = STRES(IELEM)
        STRAN(IELEM) = (DISP2-DISP1)/ELENG(IELEM)
        TSTRN(IELEM) = TSTRN(IELEM) + STRAN(IELEM)

        STRES(IELEM) = STRES(IELEM) &
                    + (STRAN(IELEM)-VIVEL(IELEM)*DTIME)*YOUNG(IELEM)
        
        TAUVE = 1.d0/(GAMA1(IELEM)*YONG0(IELEM))
        IXCSI = -DTIME/(2.d0*TAUVE)
        
        if(ISTEP == 1) DASH1(IELEM) = STRES(IELEM)
        HISTY(IELEM) = EXP(IXCSI) &
                    * (EXP(IXCSI)*DASH1(IELEM)-YONG1(IELEM)*FLUEN(IELEM))
        
        
        if(ISTEP == 1) FLUEN(IELEM) = FLUEN(IELEM) + (STRES(IELEM)-LASTS(IELEM))/(YONG0(IELEM)+YONG1(IELEM))
        !if(ISTEP == 1 .AND. IINCS /=1 ) FLUEN(IELEM) = FLUEN(IELEM) + (STRES(IELEM)-LASTS(IELEM))/(YONG0(IELEM)+YONG1(IELEM))
        if(ISTEP == 1 .AND. IINCS ==1) STRAN(IELEM) = STRAN(IELEM) + FLUEN(IELEM)
        if(ISTEP == 1 .AND. IINCS ==1) TSTRN(IELEM) = TSTRN(IELEM) + FLUEN(IELEM)
        

        if(ISTEP == 1 .AND. IINCS /=1) STRAN(IELEM) = STRAN(IELEM) + (FLUEN(IELEM) - LASTF(IELEM))
        if(ISTEP == 1 .AND. IINCS /=1) TSTRN(IELEM) = TSTRN(IELEM) + (FLUEN(IELEM) - LASTF(IELEM))
        
        LASTF(IELEM) = FLUEN(IELEM)
        FLUEN(IELEM) = FLUEN(IELEM) + VIVEL(IELEM) * DTIME
        DASH1(IELEM) = YONG1(IELEM)*EXP(IXCSI)*FLUEN(IELEM) + HISTY(IELEM) 
        
        
        SIGM1(IELEM) = STRES(IELEM)*CREPS(IELEM) &
            - CREPS(IELEM)*STRES(IELEM)*EXP(-DTIME*(1.d0-CREPS(IELEM))/TAUVE)
        
        CREPS(IELEM) = ( YONG1(IELEM) / (YONG0(IELEM) + YONG1(IELEM)) )         
        !VIVEL(IELEM)= CREPS(IELEM)**2.d0*GAMA1(IELEM)*STRES(IELEM) &
         !* EXP(-GAMA1(IELEM)*CREPS(IELEM)*YONG0(IELEM)*(TTIME))
        
        VIVEL(IELEM)=GAMA1(IELEM)*CREPS(IELEM) * (STRES(IELEM)-(YONG0(IELEM)*FLUEN(IELEM)))
        
        DELTM = TAUFT * ABS(TSTRN(IELEM) / VIVEL(IELEM))
        if(DELTM < DNEXT) DNEXT = DELTM
    end do
    
    DTIME = DNEXT
    if(ISTEP == 1) DTIME = DTINT
    
    do IELEM = 1, NELEM
        FACTR = (YOUNG(IELEM)*VIVEL(IELEM)*DTIME-STRES(IELEM))*XAREA(IELEM)
        ELOAD(IELEM,1) = -FACTR*CALFA(IELEM)
        ELOAD(IELEM,2) = -FACTR*SALFA(IELEM)
        ELOAD(IELEM,3) =  FACTR*CALFA(IELEM)
        ELOAD(IELEM,4) =  FACTR*SALFA(IELEM)
    end do
    
    ELOAD = ELOAD + TLOAD
    
END SUBROUTINE INCVE