subroutine REDFOR
    use COMMON
    use STRNFN
    implicit none

    ELOAD = 0.d0

    do IELEM = 1, NELEM

        NODE1 = LNODS(IELEM,1)
        NODE2 = LNODS(IELEM,2)
 
        DISP1=CALFA(IELEM)*XDISP(2*NODE1-1)+SALFA(IELEM)*XDISP(2*NODE1)
        DISP2=CALFA(IELEM)*XDISP(2*NODE2-1)+SALFA(IELEM)*XDISP(2*NODE2)

        DSPGX=SQRT(XDISP(2*NODE2-1)**2+XDISP(2*NODE1-1)**2)
        DSPGY=SQRT(XDISP(2*NODE2)**2+XDISP(2*NODE1)**2)
         
        STRAN(IELEM) = (DISP2-DISP1)/ELENG(IELEM)
        TSTRN(IELEM) = TSTRN(IELEM) + STRAN(IELEM)

        STRCH = 1.d0 + TSTRN(IELEM)
        STRES(IELEM) = YOUNG(IELEM)*STNFN(STRCH)
        
        FACTR = STRES(IELEM) * XAREA(IELEM)
        
        ELOAD(IELEM,1) = -FACTR*CALFA(IELEM)
        ELOAD(IELEM,2) = -FACTR*SALFA(IELEM)
        ELOAD(IELEM,3) =  FACTR*CALFA(IELEM)
        ELOAD(IELEM,4) =  FACTR*SALFA(IELEM)
    end do

    
END SUBROUTINE REDFOR
    
