SUBROUTINE INCKV
    use COMMON
    implicit none
    ELOAD = 0.d0
    DNEXT = FTIME * DTIME

    do IELEM = 1, NELEM

        NODE1 = LNODS(IELEM,1)
        NODE2 = LNODS(IELEM,2)
 
        DISP1=CALFA(IELEM)*XDISP(2*NODE1-1)+SALFA(IELEM)*XDISP(2*NODE1)
        DISP2=CALFA(IELEM)*XDISP(2*NODE2-1)+SALFA(IELEM)*XDISP(2*NODE2)

        DSPGX=SQRT(XDISP(2*NODE2-1)**2+XDISP(2*NODE1-1)**2)
        DSPGY=SQRT(XDISP(2*NODE2)**2+XDISP(2*NODE1)**2)
            
        STRAN(IELEM) = (DISP2-DISP1)/ELENG(IELEM)
        TSTRN(IELEM) = TSTRN(IELEM) + STRAN(IELEM)

        STRES(IELEM) = STRES(IELEM) &
                    + (STRAN(IELEM)-VIVEL(IELEM)*DTIME)*YOUNG(IELEM)

        DASH1(IELEM)= STRES(IELEM) - (YONG0(IELEM) * FLUEN(IELEM))

        FLUEN(IELEM) = FLUEN(IELEM) + VIVEL(IELEM) * DTIME

     
        VIVEL(IELEM) = GAMA1(IELEM) * (STRES(IELEM)-(YONG0(IELEM)*FLUEN(IELEM)))

!    ***  Limiting time-step lenght 
          DELTA = DISP2-DISP1
          EDISP = EDISP + DELTA
          SNTOT = (EDISP) / ELENG(IELEM)
          DELTM = TAUFT * ABS(SNTOT / VIVEL(IELEM))
          IF(DELTM .LT. DNEXT) DNEXT = DELTM
    end do
    
          DTIME = DNEXT
          if(ISTEP == 1) DTIME = DTINT
          
    do IELEM = 1, NELEM
        FACTR = (YOUNG(IELEM)*VIVEL(IELEM)*DTIME-STRES(IELEM))*XAREA(IELEM)
        ELOAD(IELEM,1) = -FACTR*CALFA(IELEM)
        ELOAD(IELEM,2) = -FACTR*SALFA(IELEM)
        ELOAD(IELEM,3) =  FACTR*CALFA(IELEM)
        ELOAD(IELEM,4) =  FACTR*SALFA(IELEM)
    end do
    ELOAD = ELOAD + TLOAD

END SUBROUTINE INCKV
