function VMTinpfileconstrarch(JobName, mesh, loadNodes, loadValue, fixedNodes, loaddirection)
% Gera um .inp idêntico ao exportado pelo Abaqus/CAE Learning Edition 2025
% (para o modelo "vonMisesTruss")

% --- Propriedades do material ---
E  = 2e+07;
nu = 0.3;
Area = 1.;

% --- Arquivo de saída ---
FileName = [JobName, '.inp'];
fid = fopen(FileName, 'w');
if fid == -1
    error('Erro ao criar arquivo %s', FileName);
end


%% ------------------------------------------------------------
% HEADING
% ------------------------------------------------------------
fprintf(fid, '*Heading\n');
fprintf(fid, '** Job name: VMT name: 001\n');
fprintf(fid, '** Generated by: Abaqus/CAE Learning Edition 2025\n');
fprintf(fid, '*Preprint, echo=NO, model=NO, history=NO, contact=NO\n');
fprintf(fid, '**\n');


%% ------------------------------------------------------------
% PART
% ------------------------------------------------------------
fprintf(fid, '** PARTS\n');
fprintf(fid, '**\n');
fprintf(fid, '*Part, name=Part-1\n');

% NODES
fprintf(fid, '*Node\n');
nodes = mesh.nodes;
NNODS = size(nodes,1);
for i = 1: NNODS
    fprintf(fid, '%7d, %12.4f, %12.4f\n', nodes(i,1), nodes(i,2), nodes(i,3));
end

% ELEMENTS
fprintf(fid, '*Element, type=T2D2\n');
LNODS = mesh.LNODS;
NELEM = size(LNODS,1);
for i = 1: NELEM
    fprintf(fid, '%d, %d, %d\n', LNODS(i,1), LNODS(i,2), LNODS(i,3));
end

% NSET
nodes = mesh.nodes;
fprintf(fid, '*Nset, nset=_Set1, internal, generate\n');
fprintf(fid, '1,  %d,  1\n', size(nodes,1)); %create a list 1,...,3, with increment=1

% ELSET
fprintf(fid, '*Elset, elset=_Set2, internal, generate\n'); %generate-> automatic list
fprintf(fid, '1, %d, 1\n', size(mesh.LNODS,1));

% SECTION
fprintf(fid, '** Section: Section-1\n');
fprintf(fid, '*Solid Section, elset=_Set2, material=Material-1\n');
fprintf(fid, '%.4f,\n', Area);
fprintf(fid, '*End Part\n');
fprintf(fid, '**\n');
fprintf(fid, '**\n');

%% ------------------------------------------------------------
% ASSEMBLY
% ------------------------------------------------------------
fprintf(fid, '** ASSEMBLY\n');
fprintf(fid, '**\n');
fprintf(fid, '*Assembly, name=Assembly\n');

% Part 1-1
fprintf(fid, '*Instance, name=Part-1-1, part=Part-1\n');
fprintf(fid, '*End Instance\n');
fprintf(fid, '**\n');

% --- Reference Point (to control) ---
fprintf(fid, '*Nset, nset=RP-TOP, instance=Part-1-1\n');
fprintf(fid, '%d,\n', loadNodes);

% --- Conjuntos de carga adicionais (se existirem) ---
%NLOAD=1
%for i = 1:NLOAD
%    if loadNodesAdd(i) ~= 0
%    fprintf(fid, '*Nset, nset=LoadSet%d, instance=Part-1-1\n', i);
%    fprintf(fid, ' %d,\n', loadNodesAdd(i));
%    end
%end

% --- Conjuntos de apoios fixos ---
for i = 1:length(fixedNodes)
    fprintf(fid, '*Nset, nset=BCSet%d, instance=Part-1-1\n', i);
    fprintf(fid, '%d,\n', fixedNodes(i));
end
fprintf(fid, '*End Assembly\n');
fprintf(fid, '**\n');

%% ------------------------------------------------------------
% MATERIAL
% ------------------------------------------------------------
fprintf(fid, '** MATERIALS\n');
fprintf(fid, '** \n');
fprintf(fid, '*Material, name=Material-1\n');
fprintf(fid, '*Elastic\n');
fprintf(fid, '%.1e, %.1f\n', E, nu);

%% ------------------------------------------------------------
% STEP
% ------------------------------------------------------------
fprintf(fid, '** ----------------------------------------------------------------\n');
fprintf(fid, '** \n');
fprintf(fid, '** STEP: Step-1\n');
fprintf(fid, '** \n');
fprintf(fid, '*Step, name=Step-1, nlgeom=YES, inc=10000\n');
fprintf(fid, '*Static, Riks\n');
fprintf(fid, '0.01, 1., 0.01, 0.01,\n');
fprintf(fid, '*NODE PRINT, NSET=BCSet1\n');
fprintf(fid, 'RF2\n');
fprintf(fid, '** \n');

% BOUNDARY CONDITIONS
fprintf(fid, '** BOUNDARY CONDITIONS\n');
fprintf(fid, '** \n');
for i = 1:length(fixedNodes)
    fprintf(fid, '** Name: BC-%d Type: Displacement/Rotation\n', i);
    fprintf(fid, '*Boundary\n');
    fprintf(fid, 'BCSet%d, 1, 2\n', i);  % U1,U2 constrains
end
fprintf(fid, '**\n');


% LOADS
%NLOAD=size(loadValue,1);
%for i = 1: NLOAD
    %if loadValue(i) ~= 0
    fprintf(fid, '** LOADS\n');
     fprintf(fid, '** Name: Load-1   Type: Concentrated force\n');
    fprintf(fid, '*Cload\n');
    fprintf(fid, 'RP-TOP, %d, %.1f\n', loaddirection, loadValue);
    fprintf(fid, '**\n');
    %end
%end

% OUTPUT REQUESTS
fprintf(fid, '** OUTPUT REQUESTS\n');
fprintf(fid, '** \n');
fprintf(fid, '*Restart, write, frequency=0\n');
fprintf(fid, '** \n');
fprintf(fid, '** FIELD OUTPUT: F-Output-1\n');
fprintf(fid, '** \n');
fprintf(fid, '*Output, field, variable=PRESELECT\n');
fprintf(fid, '** \n');
fprintf(fid, '** HISTORY OUTPUT: H-Output-1\n');
fprintf(fid, '** \n');
fprintf(fid, '*Output, history\n');
fprintf(fid, '*Node Output, nset=RP-TOP\n');
fprintf(fid, 'U2, CF2\n');
fprintf(fid, '*Node Output, nset=BCSet1\n');
fprintf(fid, 'RF2\n');
fprintf(fid, '*End Step\n');

fclose(fid);

fprintf('✅ Arquivo "%s" gerado com sucesso (idêntico ao Abaqus CAE)\n', FileName);end