      SUBROUTINE INCLOD
C***********************************************************************
C
C *** INPUTS DATA FOR CURRENT INCREMENT AND UPDATES LOAD VECTOR
C
C***********************************************************************

      COMMON/UNIM1/NPOIN,NELEM,NBOUN,NLOAD,NPROP,NNODE,IINCS,IITER,
     *             KRESL,NCHEK,TOLER,NALGO,NSVAB,NDOFN,NINCS,NEVAB,
     *             NSTEP,NOUTP,FACTO,PVALU
     
      COMMON/UNIM2/PROPS(5,5),COORD(26),LNODS(25,2),IFPRE(52),
     *             FIXED(52),TLOAD(25,4),RLOAD(25,4),ELOAD(25,4),
     *             MATNO(25),STRES(25,2),PLAST(25),XDISP(52),
     *             TDISP(26,2),TREAC(26,2),ASTIF(52,52),ASLOD(52),
     *             REACT(52),FRESV(1352),PEFIX(52),ESTIF(4,4)
     
      READ (5,900) NSTEP,NOUTP,FACTO,TOLER
  900 FORMAT(2I5,2F15.5)
      WRITE(6,905) IINCS,NSTEP,NOUTP,FACTO,TOLER
  905 FORMAT(1H0,5X,'IINCS =',I5,3X,'NSTEP =',I5,3X,'NOUTP =',I5,
     *       3X,'FACTO =',E14.6,3X,'TOLER =',E14.6)
      DO 10 IELEM=1,NELEM
      DO 10 IEVAB=1,NEVAB
       ELOAD(IELEM,IEVAB)=ELOAD(IELEM,IEVAB)+RLOAD(IELEM,IEVAB)*FACTO
       TLOAD(IELEM,IEVAB)=TLOAD(IELEM,IEVAB)+RLOAD(IELEM,IEVAB)*FACTO
  10  CONTINUE
      RETURN
      END